baseURL: "/"
languageCode: "en-us"
title: "hugo-journal"
theme: "journal"

permalinks:
  posts: :filename/

params:
  author: "Journal" # Author named displayed in the footer and in the posts
  heroTitle: "Journal" # Site title used in the banner
  heroSubtitle: "A minimal hugo theme" # Site subtitle used in the banner
  recentPosts: 3 # No. of posts to show under recent posts
  githubUsername: "gohugoio" # Github username to show in the footer
  logo: "https://rawcdn.githack.com/ashleymcnamara/gophers/4ddd92f3f0830f5d9a9eab50c410878249fe6515/BLUE_GOPHER.png?min=1" # Used in the banner

menu:
  main:
    - name: "Posts"
      url: "/posts/"
      weight: 1
    - name: "RSS"
      url: "/index.xml"
      weight: 2

markup.highlight.noClasses: false

markup:
  goldmark:
    renderer:
      unsafe: true
