examplesite: ../static ../layouts ../images
	cp config.yml ../config.yml
	rm -rf themes/journal
	mkdir -p themes/journal
	cp ../archetypes themes/journal -r
	cp ../images themes/journal -r
	cp ../layouts themes/journal -r
	cp ../static themes/journal -r
	cp ../theme.toml themes/journal
	cp ../config.yml config.yml
	hugo